### PR TITLE
To1.2

### PR DESCRIPTION
**Pull request by hisaha**
Modify for 1.2

### CODE REVIEW

**Comment by ghost** [comment]
@hisaha I would be happy to accept the e0fe219 commit, however the changing of the marker sizes is not something that is applicable to this general example repo.

**Comment by hisaha** [comment]
I have tried this sample with your large marker (2480 × 3508px), some demo shows really small 3d models. I confirmed it on 3d model on marker.
I investigate the plane.armodel is adjusted for your old small marker (226x320 px), it is too small for the large marker.
I think the best way is modifying of plane.armodel for the large marker, but I could not do it, then I propose changing the marker size. Would you please tell me you idea or comment?

**Comment by ghost** [comment]
It appears that unbeknownst to me, a colleague was in the process of updating the public samples to make them 1.2 compatible and as such this PR can no longer be merged.

To answer your question about what to do with the image, I would suggest to generally increase the scale of the asset you're using as the augmentation. By scaling the asset based on the marker, makes it easier to have arbitrary sizes for the marker. This is especially evident when a video is used as the augmentation; it's simpler to scale the augmented video than to try and scale the marker to fit the video.

**Comment by hisaha** [comment]
Thank you for your reply. I could understand it well. I will check your code for 1.2.

**Pull request closed without merging**
